apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-iafs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-iafs
    app.kubernetes.io/part-of: integ-app-grbm
  name: hacbs-test-project-iafs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-iafs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-iafs
    spec:
      containers:
      - image: quay.io/quay-or-not-to-quay/nbe-e2e-scry-tenant/integ-app-grbm/hacbs-test-project-iafs@sha256:f8fddf75171792d703d4734fde8ec9637869c02b64ebb2b04f134b72a71bfd13
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
